// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoHome.Data;

#nullable disable

namespace PhotoHome.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221226162554_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6c039566-63ec-4f57-9eae-1a60f986ff8f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            MyProperty = 0,
                            PasswordHash = "boss",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6dd8ba02-f283-4c25-b0a3-d471af0261e7",
                            TwoFactorEnabled = false,
                            UserName = "Boss"
                        });
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Catagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kitab"
                        },
                        new
                        {
                            Id = 2,
                            Name = " Kadin    "
                        },
                        new
                        {
                            Id = 3,
                            Name = " Giyim "
                        },
                        new
                        {
                            Id = 4,
                            Name = "Elbise    "
                        });
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int>("catagory_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("catagory_id");

                    b.HasIndex("user_id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=348",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 2,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=79",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 3,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=393",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 4,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=982",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 5,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=828",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 6,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=874",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 7,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=896",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 8,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=187",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 9,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=746",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 10,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=48",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 11,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=728",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 12,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=664",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 13,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=962",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 14,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=555",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 15,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=812",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 16,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=540",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 17,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=757",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 18,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=934",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 19,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=16",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 20,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=492",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 21,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=357",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 22,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=743",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 23,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=468",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 24,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=883",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 25,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=179",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 26,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=415",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 27,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=189",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 28,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=513",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 29,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=840",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 30,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=578",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 31,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=727",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 32,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=712",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 33,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=729",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 34,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=204",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 35,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=213",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 36,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=756",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 37,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=390",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 38,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=183",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 39,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=940",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 40,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=753",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 41,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=614",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 42,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=986",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 43,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=277",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 44,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=77",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 45,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=729",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 46,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=321",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 47,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=199",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 48,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=789",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 49,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=117",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 50,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=279",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoHome.Models.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Image", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.Catagory", "catagory")
                        .WithMany("Images")
                        .HasForeignKey("catagory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoHome.Models.Entity.AppUser", "user")
                        .WithMany("Images")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("catagory");

                    b.Navigation("user");
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.AppUser", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Catagory", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
