// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoHome.Data;

#nullable disable

namespace PhotoHome.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221224185934_bbbbbbinit")]
    partial class bbbbbbinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e2bca6c-6e7d-4875-9bb4-59737e5dfc19",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            MyProperty = 0,
                            PasswordHash = "boss",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c25226d4-fc2d-41c8-9410-a27b8af70b55",
                            TwoFactorEnabled = false,
                            UserName = "Boss"
                        });
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Catagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kitab"
                        },
                        new
                        {
                            Id = 2,
                            Name = " Kadin    "
                        },
                        new
                        {
                            Id = 3,
                            Name = " Giyim "
                        },
                        new
                        {
                            Id = 4,
                            Name = "Elbise    "
                        });
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int>("catagory_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("catagory_id");

                    b.HasIndex("user_id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=730",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 2,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=889",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 3,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=140",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 4,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=632",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 5,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=755",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 6,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=285",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 7,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=34",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 8,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=857",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 9,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=955",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 10,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=621",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 11,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=717",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 12,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=114",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 13,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=257",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 14,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=762",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 15,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=956",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 16,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=750",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 17,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=698",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 18,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=916",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 19,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=486",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 20,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=763",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 21,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=455",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 22,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=695",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 23,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=542",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 24,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=558",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 25,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=435",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 26,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=309",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 27,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=531",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 28,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=394",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 29,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=769",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 30,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=32",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 31,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=517",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 32,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=479",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 33,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=693",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 34,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=398",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 35,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=925",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 36,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=24",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 37,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=113",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 38,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=403",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 39,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=237",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 40,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=702",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 41,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=159",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 42,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=682",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 43,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=110",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 44,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=679",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 45,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=268",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 46,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=810",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 47,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=546",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 48,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=755",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 49,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=918",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 50,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=454",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 51,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=111",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 52,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=305",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 53,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=573",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 54,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=197",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 55,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=332",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 56,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=95",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 57,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=553",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 58,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=190",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 59,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=277",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 60,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=531",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 61,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=266",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 62,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=19",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 63,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=7",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 64,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=765",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 65,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=475",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 66,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=693",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 67,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=598",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 68,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=408",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 69,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=321",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 70,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=620",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 71,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=456",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 72,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=614",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 73,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=26",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 74,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=334",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 75,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=761",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 76,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=837",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 77,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=987",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 78,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=386",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 79,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=11",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 80,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=436",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 81,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=435",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 82,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=666",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 83,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=768",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 84,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=331",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 85,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=884",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 86,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=14",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 87,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=54",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 88,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=384",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 89,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=981",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 90,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=245",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 91,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=162",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 92,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=704",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 93,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=605",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 94,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=147",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 95,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=152",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 96,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=41",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 97,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=199",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 98,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=82",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 99,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=612",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 100,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=600",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 101,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=79",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 102,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=340",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 103,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=451",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 104,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=383",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 105,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=884",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 106,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=800",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 107,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=847",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 108,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=777",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 109,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=340",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 110,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=640",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 111,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=409",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 112,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=337",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 113,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=377",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 114,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=870",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 115,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=56",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 116,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=151",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 117,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=690",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 118,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=499",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 119,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=4",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 120,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=479",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 121,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=843",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 122,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=916",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 123,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=611",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 124,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=42",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 125,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=861",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 126,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=314",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 127,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=695",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 128,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=628",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 129,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=588",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 130,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=533",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 131,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=435",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 132,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=849",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 133,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=65",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 134,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=266",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 135,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=851",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 136,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=26",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 137,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=623",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 138,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=784",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 139,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=621",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 140,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=291",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 141,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=659",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 142,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=333",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 143,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=962",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 144,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=13",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 145,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=131",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 146,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=693",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 147,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=545",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 148,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=678",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 149,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=463",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        },
                        new
                        {
                            Id = 150,
                            DownloadCount = 24,
                            ImageUrl = "https://source.unsplash.com/random/200x200?sig=736",
                            LikeCount = 24,
                            catagoryid = 1,
                            userid = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoHome.Models.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Image", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.Catagory", "catagory")
                        .WithMany("Images")
                        .HasForeignKey("catagory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoHome.Models.Entity.AppUser", "user")
                        .WithMany("Images")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("catagory");

                    b.Navigation("user");
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.AppUser", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Catagory", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
