// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoHome.Data;

#nullable disable

namespace PhotoHome.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230120133929_inininin")]
    partial class inininin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Catagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kitab"
                        },
                        new
                        {
                            Id = 2,
                            Name = " Kadin    "
                        },
                        new
                        {
                            Id = 3,
                            Name = " Giyim "
                        },
                        new
                        {
                            Id = 4,
                            Name = "Elbise    "
                        });
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("catagory_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("user_id_liked")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("catagory_id");

                    b.HasIndex("user_id");

                    b.HasIndex("user_id_liked");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/ripe-red-strawberries-in-a-white-bowl.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/ripe-red-strawberries-against-pink.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/deli-with-cured-meat-on-hooks-and-eggs-on-counter.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/flatlay-iron-skillet-with-meat-and-other-food.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/close-up-of-a-bao-bun-on-a-wooden-table.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/camera-looks-down-on-wooden-table-with-two-bao-buns.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hands-slice-red-pepper-on-wooden-cutting-board.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/shellfish-pasta-pizza-and-italian-food.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/knife-slices-a-zucchini-in-half.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/person-enjoys-lunch-alone-in-a-sunlit-restaurant.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hand-holds-up-a-two-scoop-ice-cream-cone.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/close-up-of-seasoned-chickpeas.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/biscotti-lays-in-a-monstera-leaf.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/person-cuts-into-plate-of-pasta.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/three-spanakopita-spirals-on-textured-plate.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/two-red-cocktails-on-a-tray.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 17,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hand-holds-rainbow-carrots.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/gourmet-pasta-in-white-bowl.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 19,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/delicious-plate-of-pepperoni-pizza.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/flat-lay-of-baked-bread-with-apples-and-oats.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 21,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/freshly-baked-bread-in-hands.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 22,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/scrumptious-brunch-setting.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 23,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/bread-loaf-on-a-wooden-cutting-board.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 24,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/its-pasta-night.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 25,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/eggy-breakfast.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 26,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/a-picture-of-a-produce-stall-through-a-camera-screen.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 27,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hand-holding-a-mushroom.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 28,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/picking-strawberries.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 29,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/healthy-breakfast-time.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 30,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/two-pizzas-and-wine.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 31,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/pizza-and-wine-dinner.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 32,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/a-cocktail-with-a-touch-of-class.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 33,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/fresh-thyme-and-kitchen-scissors.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 34,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/berries-granola.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 35,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/couple-on-coffee-date.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 36,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/market-peppers.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 37,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/healthy-breakfast.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 38,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/table-for-two.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 39,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/breakfast-from-above.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 40,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/restaurant-breakfast.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 41,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hamburger-and-fries.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 42,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hotel-breakfast-room-service.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 43,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/berry-cheesecake.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 44,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/croissant-coffee.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 45,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/pizza-dough-ready-to-roll.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 46,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/cutting-board-with-veg.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 47,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/half-of-an-avocado.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 48,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/dinner-salad.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 49,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/popcicle.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 50,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/garden-carrots.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 51,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/closeup-iphone-cases.jpg?width=1200&amp;format=pjpg&amp;exif=0&amp;iptc=0",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 52,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/rack-of-blank-tshirts.jpg?width=1200&amp;format=pjpg&amp;exif=0&amp;iptc=0",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 53,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/black-bag-over-the-shoulder.jpg?width=1200&amp;format=pjpg&amp;exif=0&amp;iptc=0",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 54,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/ripe-red-strawberries-in-a-white-bowl.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 55,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/ripe-red-strawberries-against-pink.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 56,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/deli-with-cured-meat-on-hooks-and-eggs-on-counter.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 57,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/flatlay-iron-skillet-with-meat-and-other-food.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 58,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/close-up-of-a-bao-bun-on-a-wooden-table.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 59,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/camera-looks-down-on-wooden-table-with-two-bao-buns.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 60,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hands-slice-red-pepper-on-wooden-cutting-board.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 61,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/shellfish-pasta-pizza-and-italian-food.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 62,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/knife-slices-a-zucchini-in-half.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 63,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/person-enjoys-lunch-alone-in-a-sunlit-restaurant.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 64,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hand-holds-up-a-two-scoop-ice-cream-cone.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 65,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/close-up-of-seasoned-chickpeas.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 66,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/biscotti-lays-in-a-monstera-leaf.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 67,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/person-cuts-into-plate-of-pasta.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 68,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/three-spanakopita-spirals-on-textured-plate.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 69,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/two-red-cocktails-on-a-tray.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 70,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hand-holds-rainbow-carrots.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 71,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/gourmet-pasta-in-white-bowl.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 72,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/delicious-plate-of-pepperoni-pizza.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 73,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/flat-lay-of-baked-bread-with-apples-and-oats.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 74,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/freshly-baked-bread-in-hands.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 75,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/scrumptious-brunch-setting.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 76,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/bread-loaf-on-a-wooden-cutting-board.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 77,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/its-pasta-night.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 78,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/eggy-breakfast.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 79,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/a-picture-of-a-produce-stall-through-a-camera-screen.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 80,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hand-holding-a-mushroom.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 81,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/picking-strawberries.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 82,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/healthy-breakfast-time.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 83,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/two-pizzas-and-wine.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 84,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/pizza-and-wine-dinner.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 85,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/a-cocktail-with-a-touch-of-class.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 86,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/fresh-thyme-and-kitchen-scissors.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 87,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/berries-granola.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 88,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/couple-on-coffee-date.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 89,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/market-peppers.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 90,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/healthy-breakfast.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 91,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/table-for-two.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 92,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/breakfast-from-above.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 93,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/restaurant-breakfast.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 94,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hamburger-and-fries.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 95,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/hotel-breakfast-room-service.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 96,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/berry-cheesecake.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 97,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/croissant-coffee.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 98,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/pizza-dough-ready-to-roll.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 99,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/cutting-board-with-veg.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 100,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/half-of-an-avocado.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 101,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/dinner-salad.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 102,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/popcicle.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 103,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/garden-carrots.jpg?width=1200&amp;format=pjpg&amp;exif=1&amp;iptc=1",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 104,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/closeup-iphone-cases.jpg?width=1200&amp;format=pjpg&amp;exif=0&amp;iptc=0",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 105,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/rack-of-blank-tshirts.jpg?width=1200&amp;format=pjpg&amp;exif=0&amp;iptc=0",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 106,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://burst.shopifycdn.com/photos/black-bag-over-the-shoulder.jpg?width=1200&amp;format=pjpg&amp;exif=0&amp;iptc=0",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        });
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoHome.Models.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Picture", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.Catagory", "catagory")
                        .WithMany("Images")
                        .HasForeignKey("catagory_id");

                    b.HasOne("PhotoHome.Models.Entity.User", "user")
                        .WithMany("Created_Images")
                        .HasForeignKey("user_id");

                    b.HasOne("PhotoHome.Models.Entity.User", "user_liked")
                        .WithMany("Liked_Images")
                        .HasForeignKey("user_id_liked");

                    b.Navigation("catagory");

                    b.Navigation("user");

                    b.Navigation("user_liked");
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Catagory", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.User", b =>
                {
                    b.Navigation("Created_Images");

                    b.Navigation("Liked_Images");
                });
#pragma warning restore 612, 618
        }
    }
}
