// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoHome.Data;

#nullable disable

namespace PhotoHome.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230117172313_initisdf")]
    partial class initisdf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Catagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kitab"
                        },
                        new
                        {
                            Id = 2,
                            Name = " Kadin    "
                        },
                        new
                        {
                            Id = 3,
                            Name = " Giyim "
                        },
                        new
                        {
                            Id = 4,
                            Name = "Elbise    "
                        });
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("catagory_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("user_id_liked")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("catagory_id");

                    b.HasIndex("user_id");

                    b.HasIndex("user_id_liked");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673643654783-262d176c86d4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHxwaG90by1vZi10aGUtZGF5fHx8fGVufDB8fHx8&amp;auto=format%2Ccompress&amp;fit=crop&amp;w=1000&amp;h=1000",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1668467927849-f770914911a4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDF8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673188796938-5975e079b68d?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDR8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673842449987-3c7d56e5b1cf?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDZ8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673842450064-e9a1197e1a66?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDd8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673643654783-262d176c86d4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEwfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673446932312-413e564c5640?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEzfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673380823385-75929e08ea89?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE1fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673350018635-72ce4469e0f6?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE3fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1673264730462-6b4acadcab25?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIwfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1604758536753-68fd6f23aaf7image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1516997253075-2a25da8007e7?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1648828806223-1852f704c58aimage?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1635425197470-04119ef8fe14image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673359193906-b6694fdc0139?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDJ8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 17,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673050460660-2bd7b3bb25a4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDN8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673192573046-efc73501bd5d?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDV8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 19,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673790120533-12697d88aa59?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDh8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673667617558-91300594284c?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDl8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 21,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673643203499-23c29eafead7?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDExfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 22,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673433107234-14d1a4424658?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEyfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 23,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673446932465-a67b5bdd3d4f?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE0fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 24,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673447111351-d83b5376a9d1?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE2fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 25,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673292480069-7ebbd87081f4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE4fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 26,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673126167141-3c3e59e99f54?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE5fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 27,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1668467927849-f770914911a4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDF8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 28,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673842449987-3c7d56e5b1cf?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDZ8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 29,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673790120533-12697d88aa59?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDh8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 30,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673667617558-91300594284c?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDl8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 31,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673433107234-14d1a4424658?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEyfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 32,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673446932465-a67b5bdd3d4f?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE0fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 33,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673350018635-72ce4469e0f6?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE3fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 34,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673359193906-b6694fdc0139?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDJ8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 35,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673192573046-efc73501bd5d?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDV8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 36,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673643203499-23c29eafead7?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDExfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 37,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673446932312-413e564c5640?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEzfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 38,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673380823385-75929e08ea89?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE1fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 39,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673292480069-7ebbd87081f4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE4fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 40,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1673264730462-6b4acadcab25?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIwfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 41,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1604758536753-68fd6f23aaf7image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 42,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 43,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1516997253075-2a25da8007e7?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 44,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1648828806223-1852f704c58aimage?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 45,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1635425197470-04119ef8fe14image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 46,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673050460660-2bd7b3bb25a4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDN8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 47,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673188796938-5975e079b68d?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDR8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 48,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673842450064-e9a1197e1a66?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDd8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 49,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673643654783-262d176c86d4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEwfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 50,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673447111351-d83b5376a9d1?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE2fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 51,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673126167141-3c3e59e99f54?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE5fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 52,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1642093962150-d1951187eb26image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 53,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1668467927849-f770914911a4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDF8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 54,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1664699035313-ecbbdcab73acimage?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 55,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673359193906-b6694fdc0139?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDJ8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 56,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1604758536753-68fd6f23aaf7image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 57,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 58,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1516997253075-2a25da8007e7?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 59,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1648828806223-1852f704c58aimage?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 60,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1635425197470-04119ef8fe14image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 61,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1577555332996-ef4615422a5bimage?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 62,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673050460660-2bd7b3bb25a4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDN8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 63,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1664463803851-04da02eaa782image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 64,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673188796938-5975e079b68d?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDR8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 65,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1647285210525-979466ffc225image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 66,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673192573046-efc73501bd5d?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDV8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 67,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1673842222975-f2873955e8d2image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 68,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673842449987-3c7d56e5b1cf?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDZ8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 69,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1673842222975-f2873955e8d2image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 70,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673842450064-e9a1197e1a66?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDd8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 71,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1604758536753-68fd6f23aaf7image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 72,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673790120533-12697d88aa59?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDh8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 73,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1630067068170-6dc3b96f0f40?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 74,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673667617558-91300594284c?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDl8Ym84alFLVGFFMFl8fGVufDB8fHx8&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 75,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1644497773238-4bfe9624f353image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 76,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673643654783-262d176c86d4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEwfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 77,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1604758536753-68fd6f23aaf7image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 78,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673643203499-23c29eafead7?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDExfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 79,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1662028865407-6df71fad63a3image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 80,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673433107234-14d1a4424658?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEyfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 81,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1662762270762-06d6156dc577image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 82,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673446932312-413e564c5640?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEzfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 83,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1662762270762-06d6156dc577image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 84,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673446932465-a67b5bdd3d4f?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE0fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 85,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1557995124272-d62d831ec026?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 86,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673380823385-75929e08ea89?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE1fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 87,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1662762270762-06d6156dc577image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 88,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673447111351-d83b5376a9d1?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE2fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 89,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1584911053267-6be58094ce41image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 90,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673350018635-72ce4469e0f6?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE3fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 91,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1577555332996-ef4615422a5bimage?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 92,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673292480069-7ebbd87081f4?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE4fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 93,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1660203829473-fcd6e34021b1image?auto=format&amp;fit=crop&amp;w=32&amp;h=32&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 94,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1673126167141-3c3e59e99f54?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE5fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 95,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://images.unsplash.com/profile-1666172203856-ceab0ceadcb7image?auto=format&amp;fit=crop&amp;w=16&amp;h=16&amp;q=60&amp;crop=faces&amp;bg=fff",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        },
                        new
                        {
                            Id = 96,
                            Description = "Bomba",
                            DownloadCount = 24,
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1673264730462-6b4acadcab25?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIwfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&amp;w=1000&amp;q=80",
                            LikeCount = 24,
                            Title = "Super",
                            catagoryid = 1
                        });
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoHome.Models.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Picture", b =>
                {
                    b.HasOne("PhotoHome.Models.Entity.Catagory", "catagory")
                        .WithMany("Images")
                        .HasForeignKey("catagory_id");

                    b.HasOne("PhotoHome.Models.Entity.User", "user")
                        .WithMany("Created_Images")
                        .HasForeignKey("user_id");

                    b.HasOne("PhotoHome.Models.Entity.User", "user_liked")
                        .WithMany("Liked_Images")
                        .HasForeignKey("user_id_liked");

                    b.Navigation("catagory");

                    b.Navigation("user");

                    b.Navigation("user_liked");
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.Catagory", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("PhotoHome.Models.Entity.User", b =>
                {
                    b.Navigation("Created_Images");

                    b.Navigation("Liked_Images");
                });
#pragma warning restore 612, 618
        }
    }
}
